### PR TITLE
code_chef problem minimum attendence using c++

### PR DESCRIPTION
**Pull request by shrishail356**

### CODE REVIEW

**Comment by shrishail356** [comment]
plz add the hacktoberfest able while merging as it  will display exculded

**Review by Lancelot03 — APPROVED** [review]

**Comment by Lancelot03** [comment]
_Thanks For Contributing_ @shrishail356

**Comment by shrishail356** [comment]
bro can you pzl add the hacktober fest lable also 🙏

**Comment by shrishail356** [comment]
thank you

**Pull request merged**
